import type { ProjectMedia } from "@/content/projects";

export const musica_en_directo_cover: ProjectMedia =
{
      id: "musica-en-directo-01",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-01.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoQABgAPzmIvlSvKSajMAgB4CcJaQAAW+so1aOtWPpRyYAA/uvNHIzbOk/UlM8sMLhIXBTq50e/BSFhG+pnCnB501AzoW7dbsDo4E9O+ZMNbfTWjS/pacUpq1VphXoZx2A8x9aIlmnM6dRmUg14AAAA",
      layout: "full",
      position: 1,
      altKey: "musica-en-directo-01",
      focalPoint: { x: 50, y: 65 },
    };

export const musica_en_directo_media: ProjectMedia[] = [
    {
      id: "musica-en-directo-02",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-02.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADwAwCdASoQABgAPzmIuVOvKSWisAgB4CcJbACdABjLB2v6Jjhr71kAAP6fa7+0v7oGAIemLtjwF8Y1dGbPLoq5vH6MX0zIQy14A6nulbzZym03tqEyrFjU0cJawFMgi1pF1fQIJ+V5v4wqCte3d0ndm9U6esUe5WDhtIY+PgAAAA==",
      layout: "portrait",
      position: 2,
      altKey: "musica-en-directo-02",
      focalPoint: { x: 50, y: 40 },
    },
    {
      id: "musica-en-directo-03",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-03.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoYABAAPzmIulQvKSWjMAgB4CcJZwAAQniCpOrV6tyukQ4gAP6/drS2iFAgiGO7brlppwLEqUIjOaRVaGgEzoigjClhMqG1g3ICoscM0HvY8NfXALxAAqGi072BqoIt6b79fw+5TcfjYdZAAAA=",
      layout: "wide",
      position: 3,
      altKey: "musica-en-directo-03",
    },
    {
      id: "musica-en-directo-04",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-04.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBACdASoYABAAPzmGuVOvKSWisAgB4CcJbACdL1yBo5LQnSaAcQidIufMAP1HJbXIgWUyEADp9PILaouPp3tM/BO2yKq2fsWozbelsfws9xvn64TVoEIYkbkjVd64UC8Y0xcl842TJHctxpc4R5rQRt9PJKdkW+cwaGdGYCcAM/s8lMWOgAAA",
      layout: "pair",
      position: 4,
      altKey: "musica-en-directo-04",
    },
    {
      id: "musica-en-directo-05",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-05.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABQBACdASoYABAAPzmEuVOvKKWisAgB4CcJbACdMoACrIX5z8koM6kyC8KYAP5V4unzpDdnERTnSeaqr7Ex8aGMH7zXIPKfTc+nPeRBNR0O8ID32qgTKqkAmmxQjPRuyKB7in9JU5oJ2FLZDe683H8yUGu8uTIB0mXIf+hE/QtoJguUAAA=",
      layout: "pair",
      position: 5,
      altKey: "musica-en-directo-05",
    },
    {
      id: "musica-en-directo-06",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-06.webp",
      width: 2351,
      height: 2800,
      blurDataURL: "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBQCdASoUABgAPzmSvFgvKiWjqAqp4CcJaQAAL4ecHqgDEFHeaxjCCTBx7p5ZYpmAAP6ubKD0kK5dJwutRszIoaTYPA71RMXIVjdXwe1ncBehtEoluyKm3Z0uj58XG4/WCbzJBdDYbuQB01217GHrqKVDo96sjqYBIi5QagjPI9cwYZnv85329YAAAA==",
      layout: "portrait",
      position: 6,
      altKey: "musica-en-directo-06",
    },
    {
      id: "musica-en-directo-07",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-07.webp",
      width: 2041,
      height: 2800,
      blurDataURL: "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABQBQCdASoRABgAPzmSwFmvKaajqAgB4CcJZgCdMoABqd3nZ37+WzAF2T4MwZDWFeJyRgAA/FIuMjjjIodX7jr9i+Cih4J5NF+ldUZVxwVGgrUbw5cFwCHrwXBZhCSTFCAjkjP83e3wR7bQBwGB2Y5U1R1V0VCM/kbVIsahdOzb8G28SD+4Km+uP/8VEz5Hkk1PsgXbQIyIH07nqmU1BUyygL0oAAAA",
      layout: "wide",
      position: 7,
      altKey: "musica-en-directo-07",
    },
    {
      id: "musica-en-directo-08",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-08.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoQABgAPzmKulQvKaWjMAgB4CcJbACdACHflCMGeoFSJi42AP7i7iMGMGZ8TF3ehgcWomcnN7jjQ1odkun/wQW/fz5rcs1RBIWJJCm2GCNOyt/j8vkbXuj2juCwiNi3bTwR2DCMqTZPkzRH8Mmc6UfrV/DwuqYxwpfSBCItS/wxAwAA",
      layout: "pair",
      position: 8,
      altKey: "musica-en-directo-08",
    },
    {
      id: "musica-en-directo-09",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-09.webp",
      width: 2209,
      height: 2800,
      blurDataURL: "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAABQBQCdASoTABgAPzmEvFcvJ6WjsBgIAeAnCWwAtRAAADlaH8qdoYJ4O16yerfZi6pauAAA/ui4kMta70fZl4qGoomobQdCC7oZckUKNK0V7H5Qn+vH2mN66oPVed71wsVD+bgLP6lw7n+95nsgLs+uEZFC4sC2vmkasKX3KRFCZlH2597GNGzryBi7EqZfg2y/1Aiphr+G4/untAMhDrvNE9/7X3aBMX+jeJ8X+jeK6L31gAA=",
      layout: "pair",
      position: 9,
      altKey: "musica-en-directo-09",
    },
    {
      id: "musica-en-directo-10",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-10.webp",
      width: 2491,
      height: 2800,
      blurDataURL: "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBQCdASoVABgAPzmQvFgvKaWjqAqp4CcJbAC/OBEbXXFw1Pbs6PouIaeIV1hP2NLPqMAA/qHhbuo72J5KuRAlNarrNGURtA7k4jJSyvxI+AakkwoElYRekUXAOBhmf3CFhFkQne3aoNo2HMSxI6oWK0UO/8/jT/9zJWLqyIs+YfNPtIg4fve5z/KqGqJ2oaOeioAA",
      layout: "pair",
      position: 10,
      altKey: "musica-en-directo-10",
    },
    {
      id: "musica-en-directo-11",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-11.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoQABgAPzmEuVOvKKWisAgB4CcJbACdACHeomNXI2rGN7LwgAD+nmB3M2sGF2gPfqGoCrjS9lR7bY1v5rFK2bRXj3rE1trea7NjRmoOyM8TH1PCRGDBNMPGsojAwiPhgaY8O9VlZW5KC/U8A1+UAAAA",
      layout: "pair",
      position: 11,
      altKey: "musica-en-directo-11",
    },
    {
      id: "musica-en-directo-12",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-12.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoQABgAPzmGu1OvKSYisAgB4CcJbACdMoR3N6SEJOIgEyYJFPGJGW4AAP6FSrSpkNCckUMnwK6Oz8zf9+px9p8zJrboTxXOo1F8mksLj2zjTnGDadBdqi3aJpOSDjcfO3qSd+R9GP9SQZEmc7PPq3ae4+QAAA==",
      layout: "wide",
      position: 12,
      altKey: "musica-en-directo-12",
    },
    {
      id: "musica-en-directo-13",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-13.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBACdASoYABAAPzmEuVOvKKWisAgB4CcJbACdBagAtacLx88YBGsGVAAA/rWGI1qd+Io+Om/qR6PeLtBbNJKt6/u+vcJSE3zcdk+flo/YUFhJ1wQkTDzHALWctOR+2BTiQkseU6HeLYEoVax+T+u0kLzU1MxdSNKetQU9wHsJJIAA",
      layout: "wide",
      position: 13,
      altKey: "musica-en-directo-13",
    },
    {
      id: "musica-en-directo-14",
      type: "image",
      src: "/media/projects/musica-en-directo/musica-en-directo-14.webp",
      width: 2800,
      height: 1980,
      blurDataURL: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBQCdASoYABEAPzmUwFmvKiajqAgB4CcJYwC4MdwAbeffvSKnpmGbcfOoBGVk/uYAAP7ccXPPPSOezVBLE8fgB8hiWtf1jkG21WxyYjxA53XniCXrd5qoGWOE0u3rhuKnXlC9RzIknK/ykyxqfu3u9+c1lhtFGlOejiGtxHPQZ+uOBRAsck6Wf1TAAAAA",
      layout: "full",
      position: 14,
      altKey: "musica-en-directo-14",
      focalPoint: { x: 55, y: 38 },
    }
];

export const estudio_editorial_cover: ProjectMedia =
{
      id: "estudio-editorial-01",
      type: "image",
      src: "/media/projects/estudio-editorial/estudio-editorial-01.webp",
      width: 2800,
      height: 1947,
      blurDataURL: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwBACdASoYABEAPy1+ulOuqCYisAwB0CWJZAC3uCIAUevVrp74RI9YGhocoAD+5x//T+7ySlRBySDf13/FV11Xkunu5ahPwl1Lbx8R7IKmueV/bgaFP5EkOgTHMjbYjHmAvn0L+kQV7mLtXzuQkeR3W/jEAhwA",
      layout: "full",
      position: 1,
      altKey: "estudio-editorial-01",
    };

export const estudio_editorial_media: ProjectMedia[] = [
    {
      id: "estudio-editorial-02",
      type: "image",
      src: "/media/projects/estudio-editorial/estudio-editorial-02.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBACdASoYABAAPzmKulQvKaWjMAgB4CcJZgDCoDZDADg8RZZ+JCYXmmlAAP7es1OBshKmezyE+uyETUwcrEs5NjW+NojRLDl12eEwmK5ychhyA7ulUgvBiYDABuiVIjSsDHtJ3cNjB6hVrqYJ/uax//KkdBq1BUF9jPAAAAA=",
      layout: "wide",
      position: 2,
      altKey: "estudio-editorial-02",
    },
    {
      id: "estudio-editorial-03",
      type: "image",
      src: "/media/projects/estudio-editorial/estudio-editorial-03.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACQBACdASoYABAAPzmKu1SvKaYjMAgB4CcJQBOmUAS16UdNvs+CVnefp8yjowAA/vN5heJC044izL04etb7VGoqAqZeeGH732CyBOZbPV9UJjz+cEMy/CY1Wkpy8br1MIMkE2C+iUcmTF4oWldqbXwgAAA=",
      layout: "wide",
      position: 3,
      altKey: "estudio-editorial-03",
    },
    {
      id: "estudio-editorial-04",
      type: "image",
      src: "/media/projects/estudio-editorial/estudio-editorial-04.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQBACdASoYABAAPzmIulQvKSWjMAgB4CcJYwCo9CHiAhLKtPIcuHm5COYAAP60xndCNYDLlkOSmADqHrs6czNJZ+zHHYEbi/seLNC3+wl5XNz4AAA=",
      layout: "pair",
      position: 4,
      altKey: "estudio-editorial-04",
    },
    {
      id: "estudio-editorial-05",
      type: "image",
      src: "/media/projects/estudio-editorial/estudio-editorial-05.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQBACdASoYABAAPzmGulOvKSWisAgB4CcJZQCw7B6OlbxIlfx5MBRkAAD+r5sVpGl61dM/AX0GjHsve3pbW1Oh1gmtUMKLCBpPyR00m+dalHyKVTKmKWqdKMEs0AAA",
      layout: "pair",
      position: 5,
      altKey: "estudio-editorial-05",
    },
    {
      id: "estudio-editorial-06",
      type: "image",
      src: "/media/projects/estudio-editorial/estudio-editorial-06.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQBACdASoQABgAPzmGuVOvKSWisAgB4CcJYwDE2CHeWMhXki4XYziu86jgAP61whzAglDqXJGGAtz4prCp1ct0X2rk+PocYPVQTC88EzuQpw26xrb6z/XNSPqfgpjuffCpjCObsu4IyxQlzaDVj3nGuqeohDAA",
      layout: "wide",
      position: 6,
      altKey: "estudio-editorial-06",
    },
    {
      id: "estudio-editorial-07",
      type: "image",
      src: "/media/projects/estudio-editorial/estudio-editorial-07.webp",
      width: 2155,
      height: 2800,
      blurDataURL: "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADQBACdASoSABgAPzmQu1gvKaWjqAqp4CcJQBf9ghpJ7H8XyAmHSH4F6rjYm3/YAAD+w5Reox0KclDM/i7l2IEfhBFi8uim2Ee3WL5DoJCyImTdg7zFb3d8pKxBOAkRc0JyqD4bWp7Glrd7zFIozmRdystLWmOw5HfPC3GFoaVxcP/LQeWAAA==",
      layout: "portrait",
      position: 7,
      altKey: "estudio-editorial-07",
    },
    {
      id: "estudio-editorial-08",
      type: "image",
      src: "/media/projects/estudio-editorial/estudio-editorial-08.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoQABgAPzmEulOvKKWisAgB4CcJZQAAW+jJKe7SEwvic9L4AP6QRDyM26xLLzzDAJwgOycVxh5IBBih2/yB8DD+xH/PVtZFo71qINJkWZ3vXUxem/CApqK8AAA=",
      layout: "wide",
      position: 8,
      altKey: "estudio-editorial-08",
    },
    {
      id: "estudio-editorial-09",
      type: "image",
      src: "/media/projects/estudio-editorial/estudio-editorial-09.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwBACdASoYABAAPzmGuVOvKSWisAgB4CcJQBj8sYTb9mPzPtV0ycb57inxgAD+003YAwtbhVSSplleqLF9crUfaZIRU567bJvH5/YO4V4p3xkJ8qKTqCl4JTM8VRE4oDI6SUIYV8Nrk38jB9A7wBCAAAA=",
      layout: "pair",
      position: 9,
      altKey: "estudio-editorial-09",
    },
    {
      id: "estudio-editorial-10",
      type: "image",
      src: "/media/projects/estudio-editorial/estudio-editorial-10.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwAwCdASoYABAAPzmKu1SvKaYjMAgB4CcJZQAAUrP1lDSg6Qv2uAD+w/2vhTK/K6hdZvX+p9pRhZafsw26UAMNWVD/DXnTgzLg+qFki63EqC9KF9sdlnbdzGgAAA==",
      layout: "pair",
      position: 10,
      altKey: "estudio-editorial-10",
    }
];

export const retrato_editorial_cover: ProjectMedia =
{
      id: "retrato-editorial-01",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-01.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADwAwCdASoYABAAPzmEuVOvKKWisAgB4CcJYwDLLYw6U0Xy38FOU8wAAPnsGtIrD9zjUTb9tSXochm7C4dY5bMrAfSzN4RBAbDMIWledNHLVnaTBOA4oqPkf1zvyi4vcPfczI3CbIfRLqyKyc3HFMhg540SRIU+ReNF54Q7ChV/wAAA",
      layout: "full",
      position: 1,
      altKey: "retrato-editorial-01",
    };

export const retrato_editorial_media: ProjectMedia[] = [
    {
      id: "retrato-editorial-02",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-02.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAwCdASoYABAAPzmGuVOvKSWisAgB4CcJZQAIFmONrtl12gPWuIAA/hZZCtBtAJKa0BD0cl+EddwXFWHvE8mW5klB/QuPD+Q454tTwSrg7GZUsmHEiUZkauNVZUc3OxbucLXr0xfiiIE8HgAAAA==",
      layout: "pair",
      position: 2,
      altKey: "retrato-editorial-02",
    },
    {
      id: "retrato-editorial-03",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-03.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABQBACdASoYABAAPzmEuVOvKKWisAgB4CcJQBdgAzwrc0F0N8xTPRJwblZAAPpHGXhZLTs9Q7/Ahc+tssDB0+D+QWRZRjukfSq7ovNVqLVFpxCccs20zIoZh4nP4QNscZKqi2dWBZl2GbE24iQ4RLk0jjLCfUAq4qsgAA==",
      layout: "pair",
      position: 3,
      altKey: "retrato-editorial-03",
      focalPoint: { x: 45, y: 30 },
    },
    {
      id: "retrato-editorial-04",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-04.webp",
      width: 2800,
      height: 2061,
      blurDataURL: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQBACdASoYABIAPzmGvVavKCYjsBgIAeAnCWMAygAQVh2oIMqCaIW43U+djVAA/ro/FBDAACS/gZbNRnYwNJ3UJ2Wza7SOyRfXs6PfmDkIyilTzmVOP/8M8Rgc2gDZzUH9K6wawfBCytzVyV0ETjiCCkfbyL9C7aeX7nIAAAA=",
      layout: "pair",
      position: 4,
      altKey: "retrato-editorial-04",
    },
    {
      id: "retrato-editorial-05",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-05.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoYABAAPzmEuVOvKKWisAgB4CcJZwAAXn8HA6pL+5V9mHQAAN4nAQBF5TobwnhA/C/6ecPMvxqKvOzImucHKWOmFYtkwAJ2UspD9SoreqO+9FTKp8UDRgEkqYLVHu7twFz2rBApnJtrZ9mynlZ+w4AA",
      layout: "pair",
      position: 5,
      altKey: "retrato-editorial-05",
    },
    {
      id: "retrato-editorial-06",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-06.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADQAwCdASoYABAAPzmEuVOvKKWisAgB4CcJbAC7AB4VIbD3NTjUhQAA/gAoQwW7G+D4X0LbcSTpMJ5+4nIXPcikdQA65XVh3X7/RRdgUAYr4q/AApERcVqsViRV+X/PGSbPU/RL8y6/N8J1Sg7Xn3HvQRXWJEmjZEtcFCuWeQRTp09y5LUHSYAA",
      layout: "pair",
      position: 6,
      altKey: "retrato-editorial-06",
    },
    {
      id: "retrato-editorial-07",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-07.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoQABgAPzmGulOvKKWisAgB4CcJbAC06CHfVZhVPUe2QpPC4AD+uZAofXTP1xGmiCXOOezKmJ6Fnq0NI10LPhrZ7LXOCqJ/MJFjmJOpTXCQyBIevO2C5H6VWXqbFnk+DW7DOwY+SwDcnWDJ5Qfq49ypmKnSfpdzagTAAA==",
      layout: "pair",
      position: 7,
      altKey: "retrato-editorial-07",
    },
    {
      id: "retrato-editorial-08",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-08.webp",
      width: 2800,
      height: 2003,
      blurDataURL: "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBQCdASoYABEAPzmQvFgvKaWqKAqp4CcJbACnFBEcsSLOa47XNhOIT8pAM+4/+1QAAP6LkliF7Ufp2mc3U+418jQ0CqJzy2Tc6ClhMaYN2zhVZLzBSq/f5N/r/WDCKkBpdW9zkMJyTjr6jMkYImQKfY2n6miz1Uk1+AL4P+lAAA==",
      layout: "pair",
      position: 8,
      altKey: "retrato-editorial-08",
      focalPoint: { x: 50, y: 30 },
    },
    {
      id: "retrato-editorial-09",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-09.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACwBACdASoYABAAPzmGuVOvKSWisAgB4CcJagCdMoCGAe8Y0tsr5zZGz+T9bjGgAP2pDhHB7Hy07XC/RGG4HLvQw+dPXrY7QlEWGZCHylxaMpLOy2BxZU6P8z8SPthFgqSBX3efW1tTS/e6JMEJgQCFcKdD7Bu3bNNYX5aB1mtokRw0NUnLjYxmT7Pt6RjY1WStV9agz2675/GOW3g0B23wwUZn1QAA",
      layout: "pair",
      position: 9,
      altKey: "retrato-editorial-09",
    },
    {
      id: "retrato-editorial-10",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-10.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAwCdASoYABAAPzmEuVOvKKWisAgB4CcJYgCdMoACWYyhX9jIAP7i+j8sXMJnz9SGMytz8oFlIexZkf7HeDmYAIuKvwZj6xjk3bsDgWxyYO952CfxMokaHXWfNYDPC+KM2qDiAAA=",
      layout: "pair",
      position: 10,
      altKey: "retrato-editorial-10",
    },
    {
      id: "retrato-editorial-11",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-11.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwBACdASoYABAAPzmEuVOvKKWisAgB4CcJaACdABjS7yBtQF6FGk8/40AA/uL4NzxGOQybkO5Kw4FHluiq6Y4DbaDB0D4RJ+YKIw9rK1Zze9H3mw7+eH++E5ZPr1ZTKVwR2aVdeKkA8/i0TpL3tkerGS6gAA==",
      layout: "pair",
      position: 11,
      altKey: "retrato-editorial-11",
    },
    {
      id: "retrato-editorial-12",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-12.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADwAwCdASoYABAAPzmEuVOvKKWisAgB4CcJQBYfv/xbJQ8B4Jd7hppAAPEyu8Kd3BXxehcMaipb5skiqX7OzGMTj+QgXxU5x2I9YLYoUljTHhdayum5f5DRvOl6+Uq1Pcon86nPIDAFutZLmWaIEWv1J9T26RbsDDIjNPv9vk+PoL6NDJeETQnid/2seASuIdUQKDhcFTbH48JJk7HYAAAA",
      layout: "wide",
      position: 12,
      altKey: "retrato-editorial-12",
    },
    {
      id: "retrato-editorial-13",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-13.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoYABAAPzmGuVOvKSWisAgB4CcJbACdACPOzjDzPN22fu+wAP6p9CjdOFZwHHsZJjuGn9Sihpc3OEkMq7pH3IVcVwG7pLligzRdkt/NGYJ2L/+0To6caLTcW0tZbiQvlGCBO5ZUvBYsakxBBiB+69x5QfO/Cled4RnvxCNA4p3xOAAA",
      layout: "wide",
      position: 13,
      altKey: "retrato-editorial-13",
    },
    {
      id: "retrato-editorial-14",
      type: "image",
      src: "/media/projects/retrato-editorial/retrato-editorial-14.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBACdASoQABgAPzmEuVOvKKWisAgB4CcJZACsACPtonp4aby/pL3zoOlUAAD+WXiXOvbQgeHC/w0GCKKwat4OQLPyVyVpQhNlbqB6288pzLJiw2gQAE9TUbaCZOUskZZYaZoVB+nmJ1YvwZKL/gAA",
      layout: "portrait",
      position: 14,
      altKey: "retrato-editorial-14",
      focalPoint: { x: 50, y: 20 },
    }
];

export const calle_documental_cover: ProjectMedia =
{
      id: "calle-documental-01",
      type: "image",
      src: "/media/projects/calle-documental/calle-documental-01.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAwCdASoYABAAPzmGuVOvKSWisAgB4CcJQBbZBDvUX0xobUsN11AA/ujF84xHKx7jh10nj4rdraPQ6BcdhqgZW2w5wopTeoAAAA==",
      layout: "full",
      position: 1,
      altKey: "calle-documental-01",
      focalPoint: { x: 60, y: 50 },
    };

export const calle_documental_media: ProjectMedia[] = [
    {
      id: "calle-documental-02",
      type: "image",
      src: "/media/projects/calle-documental/calle-documental-02.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQBACdASoYABAAPzmGu1OvKSYisAgB4CcJQBOgBAqbfeDHbT6QHyGYAAD+6NVaFblvEjPnqzJKibqNqwxkovFEqm9IwhIG9NoPL4+wNyv0+WP3d8AsuYez/uAdkhQDvz/UoAAA",
      layout: "wide",
      position: 2,
      altKey: "calle-documental-02",
    },
    {
      id: "calle-documental-03",
      type: "image",
      src: "/media/projects/calle-documental/calle-documental-03.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABQAwCdASoYABAAPzmGuVOvKSWisAgB4CcJQAAJT9JdvM/4AAD+6PDzeOWJO0EF8yJ+EbKj1momVLfzAfLonI96AAA=",
      layout: "wide",
      position: 3,
      altKey: "calle-documental-03",
    },
    {
      id: "calle-documental-04",
      type: "image",
      src: "/media/projects/calle-documental/calle-documental-04.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABwBACdASoQABgAPzmEuVOvKKWisAgB4CcJagAD5LH2+5f1CfW00BtMXuS+OAD+0DX/4GU2jmjQ3PcNDxlfKVcu99KOEw39yZ18Nrhxh8IEKjcjhEQRKq5AJMFynUnjUVzyxmPMRMDpX9LKF7nN8c0nzTd/NRgyD9u/qm+mIhM+xjVucK4LGi5AAAA=",
      layout: "portrait",
      position: 4,
      altKey: "calle-documental-04",
    },
    {
      id: "calle-documental-05",
      type: "image",
      src: "/media/projects/calle-documental/calle-documental-05.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoYABAAPzmGuVOvKSWisAgB4CcJQBOkJABKXy+OPxStm8CKgAD52aGYauASTVCTFiyVRpO5ug2zCy5ohMm42Wd+pyzwvVjKhIqBUNmlzna6DoKMxP09tUGbvPweH96MCuPhV7b9tvIyTlZbWrHucsg+/9jLUQsZDaUN+S1iN1hWaRY8SLJQdwAA",
      layout: "wide",
      position: 5,
      altKey: "calle-documental-05",
    },
    {
      id: "calle-documental-06",
      type: "image",
      src: "/media/projects/calle-documental/calle-documental-06.webp",
      width: 1867,
      height: 2800,
      aspectRatio: "2:3",
      blurDataURL: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoQABgAPzmGulOvKSWisAgB4CcJaQAAShZjeCSUSLfmgAD+qHf0I4aWReNHwyS/K4m6GWXjD44P2ygc9Z2IZ7lJ8heD4FDd68RW2QjYcYGtxnOsztKsykrJVQVxJXFOwAAAAA==",
      layout: "portrait",
      position: 6,
      altKey: "calle-documental-06",
    },
    {
      id: "calle-documental-07",
      type: "image",
      src: "/media/projects/calle-documental/calle-documental-07.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQAwCdASoYABAAPzmEuVOvKKWisAgB4CcJbAAATpFn4Mr9rvKz8UAA/qKqXs1qBmi2R//JFc7SW7ipO6RFJ58K6BWVAasyHEuSS7MM069UDEXc3j/INvUQCmuiCtyfhJ9TrTIiJPFamYqHLK5BCcCWgtLd4BGuwAA=",
      layout: "wide",
      position: 7,
      altKey: "calle-documental-07",
    },
    {
      id: "calle-documental-08",
      type: "image",
      src: "/media/projects/calle-documental/calle-documental-08.webp",
      width: 2800,
      height: 1867,
      aspectRatio: "3:2",
      blurDataURL: "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADQAwCdASoYABAAPzmGuVOvKSWisAgB4CcJYwC7ABY0zMSeK9ZaYIAA/dOYVFtZkBE+8YInXTqC5zNHXMyQDLZ67BZG6kACOeYiAFDI0BaHG58GMKOMhnQUPwKiewjzSFJbbPzNPISmdvvMBXZr7M+Cb4RHXFKyS0aRTDqosen9bXHr0sCqzAAA",
      layout: "full",
      position: 8,
      altKey: "calle-documental-08",
    }
];
